title: Jon Scheiber
description: Welcome to the playground of the world.
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
github:
  is_project_page: false
